/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edunova;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Prozor extends javax.swing.JFrame {

    /**
     * Creates new form Prozor
     */
    public Prozor() {
        //ova metoda se mora uvijek prva izvesti
        initComponents();
        
        //NAŠ KOD IDE NAKON OVDJE
        
        btnHello.setText("Reci Hello");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHello = new javax.swing.JButton();
        lblPoruka = new javax.swing.JLabel();
        btnOcisti = new javax.swing.JButton();
        btnPromjeniBoju = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnHello.setText("Hello");
        btnHello.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelloActionPerformed(evt);
            }
        });

        lblPoruka.setText("jLabel1");

        btnOcisti.setText("Očisti");
        btnOcisti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOcistiActionPerformed(evt);
            }
        });

        btnPromjeniBoju.setText("Promjeni boju");
        btnPromjeniBoju.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPromjeniBojuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPromjeniBojuMouseExited(evt);
            }
        });
        btnPromjeniBoju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromjeniBojuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblPoruka)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPromjeniBoju)
                    .addComponent(btnOcisti)
                    .addComponent(btnHello))
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHello)
                    .addComponent(lblPoruka))
                .addGap(18, 18, 18)
                .addComponent(btnOcisti)
                .addGap(42, 42, 42)
                .addComponent(btnPromjeniBoju)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHelloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelloActionPerformed
        //ovdje pišem kod koji će se izvesti kada
        //kliknem na button btnHello
        System.out.println("Hello");
        lblPoruka.setText("Hello");
        lblPoruka.setText(JOptionPane.showInputDialog("Unesi ime"));
    }//GEN-LAST:event_btnHelloActionPerformed

    private void btnOcistiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcistiActionPerformed
        lblPoruka.setText("");
    }//GEN-LAST:event_btnOcistiActionPerformed

    private void btnPromjeniBojuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromjeniBojuActionPerformed
        lblPoruka.setForeground(Color.RED);
    }//GEN-LAST:event_btnPromjeniBojuActionPerformed

    private void btnPromjeniBojuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPromjeniBojuMouseEntered
        btnPromjeniBoju.setForeground(Color.RED);
        btnPromjeniBoju.setBackground(new Color(255, 0, 255));
    }//GEN-LAST:event_btnPromjeniBojuMouseEntered

    private void btnPromjeniBojuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPromjeniBojuMouseExited
        btnPromjeniBoju.setForeground(btnHello.getForeground());
        btnPromjeniBoju.setBackground(btnHello.getBackground());
    }//GEN-LAST:event_btnPromjeniBojuMouseExited

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHello;
    private javax.swing.JButton btnOcisti;
    private javax.swing.JButton btnPromjeniBoju;
    private javax.swing.JLabel lblPoruka;
    // End of variables declaration//GEN-END:variables
}
